In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.Session()

In [2]:
data_size = 25
data_1d = np.random.normal(size=data_size)
x_input_1d = tf.placeholder(dtype=tf.float32, shape=[data_size])

In [3]:
def conv_layer_1d(input_1d, my_filter):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1,1,1,1], padding="VALID")
    conv_output_1d = tf.squeeze(convolution_output)
    return(conv_output_1d)
my_filter = tf.Variable(tf.random_normal(shape=[1,5,1,1]))
my_convolution_output = conv_layer_1d(x_input_1d, my_filter)

In [4]:
def activation(input_1d):
    return(tf.nn.relu(input_1d))
my_activation_output = activation(my_convolution_output)

In [5]:
def max_pool(input_1d, width):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, 1, width, 1],
                                 strides=[1, 1, 1, 1],
                                 padding='VALID')
    pool_output_1d = tf.squeeze(pool_output)
    return(pool_output_1d)
my_maxpool_output = max_pool(my_activation_output, width=5)

In [6]:
def fully_connected(input_layer, num_outputs):
    weight_shape = tf.squeeze(tf.stack([tf.shape(input_layer),[num_outputs]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_outputs])
    input_layer_2d = tf.expand_dims(input_layer, 0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)
my_full_output = fully_connected(my_maxpool_output, 5)

In [7]:
init = tf.global_variables_initializer()
sess.run(init)
feed_dict = {x_input_1d: data_1d}
print('Input = array of length 25')
print('Convolution w/filter, length = 5, stride size = 1, results in an array of length 21:')
print(sess.run(my_convolution_output, feed_dict=feed_dict))
print('\nInput = the above array of length 21')
print('ReLU element wise returns the array of length 21:')
print(sess.run(my_activation_output, feed_dict=feed_dict))
print('\nInput = the above array of length 21')
print('MaxPool, window length = 5, stride size = 1, results in the array of length 17:')
print(sess.run(my_maxpool_output, feed_dict=feed_dict))
print('\nInput = the above array of length 17')
print('Fully connected layer on all four rows with five outputs:')
print(sess.run(my_full_output, feed_dict=feed_dict))

Input = array of length 25
Convolution w/filter, length = 5, stride size = 1, results in an array of length 21:
[-3.646209    0.9045732   2.32889366 -0.11598274 -0.87132847  1.44859242
 -1.76004124 -2.50407505 -1.17141294 -0.69335902  1.11122119 -4.46349525
 -0.73472703 -0.06231488  3.86247611 -1.50562584 -0.87364674 -0.68837315
 -2.46940207  2.51993799 -1.62778318]

Input = the above array of length 21
ReLU element wise returns the array of length 21:
[ 0.          0.9045732   2.32889366  0.          0.          1.44859242
  0.          0.          0.          0.          1.11122119  0.          0.
  0.          3.86247611  0.          0.          0.          0.
  2.51993799  0.        ]

Input = the above array of length 21
MaxPool, window length = 5, stride size = 1, results in the array of length 17:
[ 2.32889366  2.32889366  2.32889366  1.44859242  1.44859242  1.44859242
  1.11122119  1.11122119  1.11122119  1.11122119  3.86247611  3.86247611
  3.86247611  3.86247611  3.86247611  

In [8]:
ops.reset_default_graph()
sess = tf.Session()

In [9]:
data_size = [10,10]
data_2d = np.random.normal(size=data_size)
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [10]:
def conv_layer_2d(input_2d, my_filter):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1,2,2,1], padding="VALID")
    conv_output_2d = tf.squeeze(convolution_output)
    return(conv_output_2d)
my_filter = tf.Variable(tf.random_normal(shape=[2,2,1,1]))
my_convolution_output = conv_layer_2d(x_input_2d, my_filter)

In [11]:
def activation(input_2d):
    return(tf.nn.relu(input_2d))
my_activation_output = activation(my_convolution_output)

In [12]:
def max_pool(input_2d, width, height):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, height, width, 1],
                                 strides=[1, 1, 1, 1],
                                 padding='VALID')
    pool_output_2d = tf.squeeze(pool_output)
    return(pool_output_2d)
my_maxpool_output = max_pool(my_activation_output, width=2, height=2)

In [13]:
def fully_connected(input_layer, num_outputs):
    flat_input = tf.reshape(input_layer, [-1])
    weight_shape = tf.squeeze(tf.stack([tf.shape(flat_input),[num_outputs]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_outputs])
    input_2d = tf.expand_dims(flat_input, 0)
    full_output = tf.add(tf.matmul(input_2d, weight), bias)
    full_output_2d = tf.squeeze(full_output)
    return(full_output_2d)
my_full_output = fully_connected(my_maxpool_output, 5)

In [14]:
init = tf.global_variables_initializer()
sess.run(init)
feed_dict = {x_input_2d: data_2d}

In [15]:
print('Input = [10 X 10] array')
print('2x2 Convolution, stride size = [2x2], results in the [5x5] array:')
print(sess.run(my_convolution_output, feed_dict=feed_dict))
print('\nInput = the above [5x5] array')
print('ReLU element wise returns the [5x5] array:')
print(sess.run(my_activation_output, feed_dict=feed_dict))
print('\nInput = the above [5x5] array')
print('MaxPool, stride size = [1x1], results in the [4x4] array:')
print(sess.run(my_maxpool_output, feed_dict=feed_dict))
print('\nInput = the above [4x4] array')
print('Fully connected layer on all four rows with five outputs:')
print(sess.run(my_full_output, feed_dict=feed_dict))

Input = [10 X 10] array
2x2 Convolution, stride size = [2x2], results in the [5x5] array:
[[ 2.60103631 -1.53552842 -1.68671465  3.11533427 -3.52291489]
 [ 7.5114975  -2.48186564  0.32743108 -0.84987295 -0.38588881]
 [-0.23601067  1.22517467  0.79208016 -0.66182518 -0.22458503]
 [-1.00660574 -3.70954537 -0.0976584  -1.02609503 -2.26884246]
 [ 1.18578267 -0.60996336  1.42970955 -6.30630445  0.05838838]]

Input = the above [5x5] array
ReLU element wise returns the [5x5] array:
[[ 2.60103631  0.          0.          3.11533427  0.        ]
 [ 7.5114975   0.          0.32743108  0.          0.        ]
 [ 0.          1.22517467  0.79208016  0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 1.18578267  0.          1.42970955  0.          0.05838838]]

Input = the above [5x5] array
MaxPool, stride size = [1x1], results in the [4x4] array:
[[ 7.5114975   0.32743108  3.11533427  3.11533427]
 [ 7.5114975   1.22517467  0.79208016  0.        ]
 [ 1.22517467